# Generated by Django 6.0.6 on 2026-06-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toko", "0003_remove_profile_address_remove_profile_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
