# Generated by Django 6.0.6 on 2026-06-30 10:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toko", "0005_order_delete_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Produk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=200)),
                ("brand", models.CharField(default="Maybelline", max_length=100)),
                ("harga", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "gambar",
                    models.ImageField(blank=True, null=True, upload_to="produk/"),
                ),
                ("stok", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pesanan",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=20, primary_key=True, serialize=False
                    ),
                ),
                (
                    "tanggal_pesan",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("menunggu", "Menunggu"),
                            ("dikemas", "Dikemas"),
                            ("dikirim", "Dikirim"),
                            ("selesai", "Selesai"),
                            ("dibatalkan", "Dibatalkan"),
                        ],
                        default="menunggu",
                        max_length=20,
                    ),
                ),
                ("alamat_pengiriman", models.TextField()),
                ("catatan", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pesanan",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PesananItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jumlah", models.IntegerField(default=1)),
                ("harga", models.DecimalField(decimal_places=2, max_digits=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pesanan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="toko.pesanan",
                    ),
                ),
                (
                    "produk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="toko.produk"
                    ),
                ),
            ],
        ),
    ]
