# Generated by Django 6.0.6 on 2026-06-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toko", "0006_produk_pesanan_pesananitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produk",
            name="gambar",
        ),
        migrations.RemoveField(
            model_name="produk",
            name="harga",
        ),
        migrations.RemoveField(
            model_name="produk",
            name="nama",
        ),
        migrations.RemoveField(
            model_name="produk",
            name="stok",
        ),
        migrations.AddField(
            model_name="produk",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="produk",
            name="id_api",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="produk",
            name="image_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="produk",
            name="name",
            field=models.CharField(default="Produk Maybelline", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produk",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="produk",
            name="product_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="produk",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="produk",
            name="brand",
            field=models.CharField(max_length=100),
        ),
    ]
